//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.01 at 11:53:19 PM IST 
//


package bfs.soap.siemens.com.webbfs_soap_server;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BfsObj complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BfsObj">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ObjVal" type="{http://com.siemens.soap.bfs/webbfs-soap-server}ArrayOfObjVal" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="TabNam" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BfsObj", propOrder = {
    "objVal",
    "tabNam"
})
public class BfsObj {

    @XmlElement(name = "ObjVal")
    protected List<ArrayOfObjVal> objVal;
    @XmlElement(name = "TabNam", required = true)
    protected String tabNam;

    /**
     * Gets the value of the objVal property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the objVal property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getObjVal().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ArrayOfObjVal }
     * 
     * 
     */
    public List<ArrayOfObjVal> getObjVal() {
        if (objVal == null) {
            objVal = new ArrayList<ArrayOfObjVal>();
        }
        return this.objVal;
    }

    /**
     * Gets the value of the tabNam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTabNam() {
        return tabNam;
    }

    /**
     * Sets the value of the tabNam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTabNam(String value) {
        this.tabNam = value;
    }

}
