//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.01 at 11:53:19 PM IST 
//


package bfs.soap.siemens.com.webbfs_soap_server;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SearchVal complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SearchVal">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="CloneNum" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Group" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="LinkOR" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Operator" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="OperatorNot" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="TabAndCol" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SearchVal", propOrder = {
    "cloneNum",
    "group",
    "linkOR",
    "operator",
    "operatorNot",
    "tabAndCol",
    "value"
})
public class SearchVal {

    @XmlElement(name = "CloneNum", required = true)
    protected String cloneNum;
    @XmlElement(name = "Group", required = true)
    protected String group;
    @XmlElement(name = "LinkOR", required = true)
    protected String linkOR;
    @XmlElement(name = "Operator", required = true)
    protected String operator;
    @XmlElement(name = "OperatorNot", required = true)
    protected String operatorNot;
    @XmlElement(name = "TabAndCol", required = true)
    protected String tabAndCol;
    @XmlElement(name = "Value", required = true)
    protected String value;

    /**
     * Gets the value of the cloneNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCloneNum() {
        return cloneNum;
    }

    /**
     * Sets the value of the cloneNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCloneNum(String value) {
        this.cloneNum = value;
    }

    /**
     * Gets the value of the group property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGroup() {
        return group;
    }

    /**
     * Sets the value of the group property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGroup(String value) {
        this.group = value;
    }

    /**
     * Gets the value of the linkOR property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkOR() {
        return linkOR;
    }

    /**
     * Sets the value of the linkOR property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkOR(String value) {
        this.linkOR = value;
    }

    /**
     * Gets the value of the operator property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperator() {
        return operator;
    }

    /**
     * Sets the value of the operator property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperator(String value) {
        this.operator = value;
    }

    /**
     * Gets the value of the operatorNot property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOperatorNot() {
        return operatorNot;
    }

    /**
     * Sets the value of the operatorNot property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOperatorNot(String value) {
        this.operatorNot = value;
    }

    /**
     * Gets the value of the tabAndCol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTabAndCol() {
        return tabAndCol;
    }

    /**
     * Sets the value of the tabAndCol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTabAndCol(String value) {
        this.tabAndCol = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

}
