//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.25 at 01:36:04 PM IST 
//


package bfs.soap.siemens.com.webbfs_soap_server;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SearchObjectsResult complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SearchObjectsResult">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="DBServer" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="DBUser" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ListOf_BfsObj" type="{http://com.siemens.soap.bfs/webbfs-soap-server}ArrayOfBfsObj"/>
 *         &lt;element name="ListOf_LinkInfos" type="{http://com.siemens.soap.bfs/webbfs-soap-server}ArrayOfLinkInfos"/>
 *         &lt;element name="TabNam" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="Total" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SearchObjectsResult", propOrder = {
    "dbServer",
    "dbUser",
    "listOfBfsObj",
    "listOfLinkInfos",
    "tabNam",
    "total"
})
public class SearchObjectsResult {

    @XmlElement(name = "DBServer", required = true)
    protected String dbServer;
    @XmlElement(name = "DBUser", required = true)
    protected String dbUser;
    @XmlElement(name = "ListOf_BfsObj", required = true)
    protected ArrayOfBfsObj listOfBfsObj;
    @XmlElement(name = "ListOf_LinkInfos", required = true)
    protected ArrayOfLinkInfos listOfLinkInfos;
    @XmlElement(name = "TabNam", required = true)
    protected String tabNam;
    @XmlElement(name = "Total")
    protected int total;

    /**
     * Gets the value of the dbServer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDBServer() {
        return dbServer;
    }

    /**
     * Sets the value of the dbServer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDBServer(String value) {
        this.dbServer = value;
    }

    /**
     * Gets the value of the dbUser property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDBUser() {
        return dbUser;
    }

    /**
     * Sets the value of the dbUser property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDBUser(String value) {
        this.dbUser = value;
    }

    /**
     * Gets the value of the listOfBfsObj property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfBfsObj }
     *     
     */
    public ArrayOfBfsObj getListOfBfsObj() {
        return listOfBfsObj;
    }

    /**
     * Sets the value of the listOfBfsObj property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfBfsObj }
     *     
     */
    public void setListOfBfsObj(ArrayOfBfsObj value) {
        this.listOfBfsObj = value;
    }

    /**
     * Gets the value of the listOfLinkInfos property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfLinkInfos }
     *     
     */
    public ArrayOfLinkInfos getListOfLinkInfos() {
        return listOfLinkInfos;
    }

    /**
     * Sets the value of the listOfLinkInfos property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfLinkInfos }
     *     
     */
    public void setListOfLinkInfos(ArrayOfLinkInfos value) {
        this.listOfLinkInfos = value;
    }

    /**
     * Gets the value of the tabNam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTabNam() {
        return tabNam;
    }

    /**
     * Sets the value of the tabNam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTabNam(String value) {
        this.tabNam = value;
    }

    /**
     * Gets the value of the total property.
     * 
     */
    public int getTotal() {
        return total;
    }

    /**
     * Sets the value of the total property.
     * 
     */
    public void setTotal(int value) {
        this.total = value;
    }

}
