//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.24 at 11:47:04 PM IST 
//


package bfs.soap.siemens.com.webbfs_soap_server;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for Link complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Link"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="CloneNum" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="LinkNum" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="TabNam" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Link", propOrder = {
    "cloneNum",
    "linkNum",
    "tabNam"
})
public class Link {

    @XmlElement(name = "CloneNum", required = true)
    protected String cloneNum;
    @XmlElement(name = "LinkNum", required = true)
    protected String linkNum;
    @XmlElement(name = "TabNam", required = true)
    protected String tabNam;

    /**
     * Gets the value of the cloneNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCloneNum() {
        return cloneNum;
    }

    /**
     * Sets the value of the cloneNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCloneNum(String value) {
        this.cloneNum = value;
    }

    /**
     * Gets the value of the linkNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkNum() {
        return linkNum;
    }

    /**
     * Sets the value of the linkNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkNum(String value) {
        this.linkNum = value;
    }

    /**
     * Gets the value of the tabNam property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTabNam() {
        return tabNam;
    }

    /**
     * Sets the value of the tabNam property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTabNam(String value) {
        this.tabNam = value;
    }

}
