//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.24 at 11:47:04 PM IST 
//


package bfs.soap.siemens.com.webbfs_soap_server;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the bfs.soap.siemens.com.webbfs_soap_server package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: bfs.soap.siemens.com.webbfs_soap_server
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link SearchObjects }
     * 
     */
    public SearchObjects createSearchObjects() {
        return new SearchObjects();
    }

    /**
     * Create an instance of {@link SearchCrit }
     * 
     */
    public SearchCrit createSearchCrit() {
        return new SearchCrit();
    }

    /**
     * Create an instance of {@link SelectList }
     * 
     */
    public SelectList createSelectList() {
        return new SelectList();
    }

    /**
     * Create an instance of {@link SearchObjectsResponse }
     * 
     */
    public SearchObjectsResponse createSearchObjectsResponse() {
        return new SearchObjectsResponse();
    }

    /**
     * Create an instance of {@link SearchObjectsResult }
     * 
     */
    public SearchObjectsResult createSearchObjectsResult() {
        return new SearchObjectsResult();
    }

    /**
     * Create an instance of {@link ArrayOfSearchVal }
     * 
     */
    public ArrayOfSearchVal createArrayOfSearchVal() {
        return new ArrayOfSearchVal();
    }

    /**
     * Create an instance of {@link SearchVal }
     * 
     */
    public SearchVal createSearchVal() {
        return new SearchVal();
    }

    /**
     * Create an instance of {@link ArrayOfLinks }
     * 
     */
    public ArrayOfLinks createArrayOfLinks() {
        return new ArrayOfLinks();
    }

    /**
     * Create an instance of {@link Link }
     * 
     */
    public Link createLink() {
        return new Link();
    }

    /**
     * Create an instance of {@link ArrayOfSelectCols }
     * 
     */
    public ArrayOfSelectCols createArrayOfSelectCols() {
        return new ArrayOfSelectCols();
    }

    /**
     * Create an instance of {@link SelectCol }
     * 
     */
    public SelectCol createSelectCol() {
        return new SelectCol();
    }

    /**
     * Create an instance of {@link ArrayOfBfsObj }
     * 
     */
    public ArrayOfBfsObj createArrayOfBfsObj() {
        return new ArrayOfBfsObj();
    }

    /**
     * Create an instance of {@link BfsObj }
     * 
     */
    public BfsObj createBfsObj() {
        return new BfsObj();
    }

    /**
     * Create an instance of {@link ArrayOfObjVal }
     * 
     */
    public ArrayOfObjVal createArrayOfObjVal() {
        return new ArrayOfObjVal();
    }

    /**
     * Create an instance of {@link ObjVal }
     * 
     */
    public ObjVal createObjVal() {
        return new ObjVal();
    }

    /**
     * Create an instance of {@link ArrayOfLinkInfos }
     * 
     */
    public ArrayOfLinkInfos createArrayOfLinkInfos() {
        return new ArrayOfLinkInfos();
    }

    /**
     * Create an instance of {@link LinkInfo }
     * 
     */
    public LinkInfo createLinkInfo() {
        return new LinkInfo();
    }

}
