//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.24 at 11:47:04 PM IST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com.siemens.soap.bfs/webbfs-soap-server", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package bfs.soap.siemens.com.webbfs_soap_server;
