//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.25 at 01:36:16 PM IST 
//


package bfs.soap.siemens.com.webbfs_soap_server;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="mainTable" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="searchCrit" type="{http://com.siemens.soap.bfs/webbfs-soap-server}SearchCrit"/&gt;
 *         &lt;element name="selectList" type="{http://com.siemens.soap.bfs/webbfs-soap-server}SelectList"/&gt;
 *         &lt;element name="startIndex" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="endIndex" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "mainTable",
    "searchCrit",
    "selectList",
    "startIndex",
    "endIndex"
})
@XmlRootElement(name = "SearchObjects")
public class SearchObjects {

    @XmlElement(required = true)
    protected String mainTable;
    @XmlElement(required = true)
    protected SearchCrit searchCrit;
    @XmlElement(required = true)
    protected SelectList selectList;
    protected int startIndex;
    protected int endIndex;

    /**
     * Gets the value of the mainTable property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMainTable() {
        return mainTable;
    }

    /**
     * Sets the value of the mainTable property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMainTable(String value) {
        this.mainTable = value;
    }

    /**
     * Gets the value of the searchCrit property.
     * 
     * @return
     *     possible object is
     *     {@link SearchCrit }
     *     
     */
    public SearchCrit getSearchCrit() {
        return searchCrit;
    }

    /**
     * Sets the value of the searchCrit property.
     * 
     * @param value
     *     allowed object is
     *     {@link SearchCrit }
     *     
     */
    public void setSearchCrit(SearchCrit value) {
        this.searchCrit = value;
    }

    /**
     * Gets the value of the selectList property.
     * 
     * @return
     *     possible object is
     *     {@link SelectList }
     *     
     */
    public SelectList getSelectList() {
        return selectList;
    }

    /**
     * Sets the value of the selectList property.
     * 
     * @param value
     *     allowed object is
     *     {@link SelectList }
     *     
     */
    public void setSelectList(SelectList value) {
        this.selectList = value;
    }

    /**
     * Gets the value of the startIndex property.
     * 
     */
    public int getStartIndex() {
        return startIndex;
    }

    /**
     * Sets the value of the startIndex property.
     * 
     */
    public void setStartIndex(int value) {
        this.startIndex = value;
    }

    /**
     * Gets the value of the endIndex property.
     * 
     */
    public int getEndIndex() {
        return endIndex;
    }

    /**
     * Sets the value of the endIndex property.
     * 
     */
    public void setEndIndex(int value) {
        this.endIndex = value;
    }

}
