//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.02.25 at 01:36:16 PM IST 
//


package bfs.soap.siemens.com.webbfs_soap_server;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SearchCrit complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SearchCrit"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="ListOf_SearchVal" type="{http://com.siemens.soap.bfs/webbfs-soap-server}ArrayOfSearchVal"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SearchCrit", propOrder = {
    "listOfSearchVal"
})
public class SearchCrit {

    @XmlElement(name = "ListOf_SearchVal", required = true)
    protected ArrayOfSearchVal listOfSearchVal;

    /**
     * Gets the value of the listOfSearchVal property.
     * 
     * @return
     *     possible object is
     *     {@link ArrayOfSearchVal }
     *     
     */
    public ArrayOfSearchVal getListOfSearchVal() {
        return listOfSearchVal;
    }

    /**
     * Sets the value of the listOfSearchVal property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArrayOfSearchVal }
     *     
     */
    public void setListOfSearchVal(ArrayOfSearchVal value) {
        this.listOfSearchVal = value;
    }

}
