//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.0 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.03.02 at 08:14:33 PM IST 
//


package bfs.soap.siemens.com.webbfs_soap_server;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for SelectCol complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SelectCol"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="AggFun" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="CloneNum" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Null" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="OrderBy" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="TabAndCol" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="Value" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SelectCol", propOrder = {
    "aggFun",
    "cloneNum",
    "_null",
    "orderBy",
    "tabAndCol",
    "value"
})
public class SelectCol {

    @XmlElement(name = "AggFun", required = true)
    protected String aggFun;
    @XmlElement(name = "CloneNum", required = true)
    protected String cloneNum;
    @XmlElement(name = "Null", required = true)
    protected String _null;
    @XmlElement(name = "OrderBy", required = true)
    protected String orderBy;
    @XmlElement(name = "TabAndCol", required = true)
    protected String tabAndCol;
    @XmlElement(name = "Value", required = true)
    protected String value;

    /**
     * Gets the value of the aggFun property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAggFun() {
        return aggFun;
    }

    /**
     * Sets the value of the aggFun property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAggFun(String value) {
        this.aggFun = value;
    }

    /**
     * Gets the value of the cloneNum property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCloneNum() {
        return cloneNum;
    }

    /**
     * Sets the value of the cloneNum property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCloneNum(String value) {
        this.cloneNum = value;
    }

    /**
     * Gets the value of the null property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNull() {
        return _null;
    }

    /**
     * Sets the value of the null property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNull(String value) {
        this._null = value;
    }

    /**
     * Gets the value of the orderBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOrderBy() {
        return orderBy;
    }

    /**
     * Sets the value of the orderBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOrderBy(String value) {
        this.orderBy = value;
    }

    /**
     * Gets the value of the tabAndCol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTabAndCol() {
        return tabAndCol;
    }

    /**
     * Sets the value of the tabAndCol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTabAndCol(String value) {
        this.tabAndCol = value;
    }

    /**
     * Gets the value of the value property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getValue() {
        return value;
    }

    /**
     * Sets the value of the value property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setValue(String value) {
        this.value = value;
    }

}
